package com.sonicether.soundphysics;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.List;

import com.sonicether.soundphysics.config.SoundPhysicsConfig;

public final class ConfigDiagnostics {

    private ConfigDiagnostics() {
    }

    public static Path configDirectory(Path configFolder) {
        return configFolder.resolve(SoundPhysicsMod.MODID);
    }

    public static Path soundPhysicsConfigPath(Path configFolder) {
        return configDirectory(configFolder).resolve("soundphysics.properties");
    }

    public static List<String> configPathLines(Path gameDirectory, Path configFolder) {
        Path soundPhysicsConfigPath = soundPhysicsConfigPath(configFolder);
        List<String> lines = new ArrayList<>();
        lines.add("SPRA_PATCH_ID=" + SoundPhysicsMod.SPRA_PATCH_ID);
        lines.add("Game directory: " + gameDirectory.toAbsolutePath());
        lines.add("Config folder: " + configFolder.toAbsolutePath());
        lines.add("Sound Physics config folder: " + configDirectory(configFolder).toAbsolutePath());
        lines.add("soundphysics.properties: " + soundPhysicsConfigPath.toAbsolutePath());
        lines.add("soundphysics.properties exists: " + Files.isRegularFile(soundPhysicsConfigPath));
        lines.add("soundphysics.properties last modified: " + lastModifiedText(soundPhysicsConfigPath));
        lines.add("Config values: " + criticalValuesSummary());
        return lines;
    }

    public static List<String> configDumpLines(Path gameDirectory, Path configFolder) {
        List<String> lines = new ArrayList<>(configPathLines(gameDirectory, configFolder));
        lines.add("Active values:");
        lines.addAll(configValueLines());
        return lines;
    }

    public static Path exportExample(Path configFolder) throws IOException {
        Path activePath = soundPhysicsConfigPath(configFolder);
        Path examplePath = activePath.resolveSibling(activePath.getFileName() + ".example");
        Files.createDirectories(examplePath.getParent());

        List<String> lines = new ArrayList<>();
        lines.add("# Sound Physics Aeronautics active config example");
        lines.add("# Generated by /spr_aero config_export_defaults");
        lines.add("# This file is safe to inspect. It does not overwrite soundphysics.properties.");
        lines.add("");
        for (String valueLine : configValueLines()) {
            lines.add(valueLine);
        }

        Files.write(examplePath, lines, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.WRITE);
        return examplePath;
    }

    public static List<String> configValueLines() {
        SoundPhysicsConfig config = SoundPhysicsMod.CONFIG;
        List<String> lines = new ArrayList<>();
        if (config == null) {
            lines.add("config=not_initialized");
            return lines;
        }

        lines.add("enabled=" + config.enabled.get());
        lines.add("render_occlusion=" + config.renderOcclusion.get());
        lines.add("render_sound_bounces=" + config.renderSoundBounces.get());
        lines.add("debug_logging=" + config.debugLogging.get());
        lines.add("occlusion_logging=" + config.occlusionLogging.get());
        lines.add("environment_logging=" + config.environmentLogging.get());
        lines.add("performance_logging=" + config.performanceLogging.get());
        lines.add("doppler_debug_logging=" + config.dopplerDebugLogging.get());
        lines.add("sound_policy_debug_logging=" + config.soundPhysicsPolicyDebugLogging.get());
        lines.add("sable_acoustic_debug_logging=" + config.sableAcousticDebugLogging.get());
        lines.add("sound_physics_trace_logging=" + config.soundPhysicsTraceLogging.get());
        lines.add("openal_error_checks=" + config.openAlErrorChecks.get());
        lines.add("adaptive_reflection_budget_enabled=" + config.adaptiveReflectionBudgetEnabled.get());
        lines.add("sable_acoustics_enabled=" + config.sableAcousticsEnabled.get());
        lines.add("force_root_acoustic_provider=" + config.forceRootAcousticProvider.get());
        lines.add("sound_physics_apply_to_weather_sounds=" + config.soundPhysicsApplyToWeatherSounds.get());
        lines.add("sound_physics_apply_to_positional_ambient_sounds=" + config.soundPhysicsApplyToPositionalAmbientSounds.get());
        lines.add("sound_physics_apply_to_positional_ambient_machinery=" + config.soundPhysicsApplyToPositionalAmbientMachinery.get());
        lines.add("sound_physics_apply_to_records=" + config.soundPhysicsApplyToRecords.get());
        lines.add("record_acoustic_update_interval_ticks=" + config.recordAcousticUpdateIntervalTicks.get());
        lines.add("sound_physics_apply_to_music=" + config.soundPhysicsApplyToMusic.get());
        lines.add("sound_physics_apply_to_crosswind_wind=" + config.soundPhysicsApplyToCrosswindWind.get());
        lines.add("sound_physics_sound_allowlist=" + config.soundPhysicsSoundAllowlist.get());
        lines.add("sound_physics_sound_denylist=" + config.soundPhysicsSoundDenylist.get());
        lines.add("doppler_enabled=" + config.dopplerEnabled.get());
        lines.add("doppler_strength=" + config.dopplerStrength.get());
        lines.add("doppler_speed_of_sound_blocks_per_second=" + config.dopplerSpeedOfSound.get());
        lines.add("doppler_min_pitch_multiplier=" + config.dopplerMinPitchMultiplier.get());
        lines.add("doppler_max_pitch_multiplier=" + config.dopplerMaxPitchMultiplier.get());
        lines.add("doppler_update_interval_ticks=" + config.dopplerUpdateIntervalTicks.get());
        lines.add("doppler_smoothing_time_ms=" + config.dopplerSmoothingTimeMs.get());
        lines.add("doppler_apply_to_block_sounds=" + config.dopplerApplyToBlockSounds.get());
        lines.add("doppler_apply_to_entity_sounds=" + config.dopplerApplyToEntitySounds.get());
        lines.add("doppler_apply_to_weather_sounds=" + config.dopplerApplyToWeatherSounds.get());
        lines.add("doppler_apply_to_ambient_sounds=" + config.dopplerApplyToAmbientSounds.get());
        lines.add("doppler_apply_to_positional_ambient_sounds=" + config.dopplerApplyToPositionalAmbientSounds.get());
        lines.add("doppler_apply_to_sable_delegated_sounds=" + config.dopplerApplyToSableDelegatedSounds.get());
        lines.add("doppler_apply_to_music=" + config.dopplerApplyToMusic.get());
        lines.add("doppler_apply_to_records=" + config.dopplerApplyToRecords.get());
        lines.add("doppler_apply_to_aeronautics_propellers=" + config.dopplerApplyToAeronauticsPropellers.get());
        lines.add("doppler_apply_to_positional_ambient_machinery=" + config.dopplerApplyToPositionalAmbientMachinery.get());
        lines.add("doppler_apply_to_crosswind_wind=" + config.dopplerApplyToCrosswindWind.get());
        lines.add("doppler_sound_allowlist=" + config.dopplerSoundAllowlist.get());
        lines.add("doppler_sound_denylist=" + config.dopplerSoundDenylist.get());
        lines.add("propeller_long_range_enabled=" + config.propellerLongRangeEnabled.get());
        lines.add("propeller_long_range_profile=" + config.propellerLongRangeProfile.get());
        lines.add("propeller_long_range_max_distance=" + config.propellerLongRangeMaxDistance.get());
        lines.add("propeller_long_range_min_distance=" + config.propellerLongRangeMinDistance.get());
        lines.add("propeller_long_range_absolute_cap_blocks=" + config.propellerLongRangeAbsoluteCapBlocks.get());
        lines.add("propeller_long_range_max_processing_distance=" + config.propellerLongRangeMaxProcessingDistance.get());
        lines.add("propeller_long_range_small_fallback_sails=" + config.propellerLongRangeSmallFallbackSails.get());
        lines.add("propeller_long_range_large_fallback_sails=" + config.propellerLongRangeLargeFallbackSails.get());
        lines.add("propeller_long_range_size_reference_sails=" + config.propellerLongRangeSizeReferenceSails.get());
        lines.add("propeller_long_range_rpm_reference=" + config.propellerLongRangeRpmReference.get());
        lines.add("propeller_long_range_size_exponent=" + config.propellerLongRangeSizeExponent.get());
        lines.add("propeller_long_range_rpm_exponent=" + config.propellerLongRangeRpmExponent.get());
        lines.add("propeller_long_range_pitch_at_reference_rpm=" + config.propellerLongRangePitchAtReferenceRpm.get());
        lines.add("propeller_long_range_reference_distance_fraction=" + config.propellerLongRangeReferenceDistanceFraction.get());
        lines.add("propeller_long_range_reference_distance_min=" + config.propellerLongRangeReferenceDistanceMin.get());
        lines.add("propeller_long_range_reference_distance_max=" + config.propellerLongRangeReferenceDistanceMax.get());
        lines.add("propeller_long_range_rolloff_factor=" + config.propellerLongRangeRolloffFactor.get());
        lines.add("propeller_long_range_apply_in_safe_mode=" + config.propellerLongRangeApplyInSafeMode.get());
        lines.add("propeller_long_range_apply_to_crosswind_vehicle_propellers=" + config.propellerLongRangeApplyToCrosswindVehiclePropellers.get());
        lines.add("propeller_long_range_close_end_blocks=" + config.propellerLongRangeCloseEndBlocks.get());
        lines.add("propeller_long_range_mid_end_blocks=" + config.propellerLongRangeMidEndBlocks.get());
        lines.add("propeller_long_range_mid_gain=" + config.propellerLongRangeMidGain.get());
        lines.add("propeller_long_range_far_min_gain=" + config.propellerLongRangeFarMinGain.get());
        lines.add("propeller_far_field_enabled=" + config.propellerFarFieldEnabled.get());
        lines.add("propeller_far_field_start_fraction=" + config.propellerFarFieldStartFraction.get());
        lines.add("propeller_far_field_start_blocks=" + config.propellerFarFieldStartBlocks.get());
        lines.add("propeller_far_field_full_blocks=" + config.propellerFarFieldFullBlocks.get());
        lines.add("propeller_far_field_start_ratio=" + config.propellerFarFieldStartRatio.get());
        lines.add("propeller_far_field_full_ratio=" + config.propellerFarFieldFullRatio.get());
        lines.add("propeller_far_field_direct_cutoff_at_max=" + config.propellerFarFieldDirectCutoffAtMax.get());
        lines.add("propeller_far_field_direct_gain_at_max=" + config.propellerFarFieldDirectGainAtMax.get());
        lines.add("propeller_far_cutoff_min=" + config.propellerFarCutoffMin.get());
        lines.add("propeller_far_field_air_absorption_bonus=" + config.propellerFarFieldAirAbsorptionBonus.get());
        lines.add("propeller_far_compensate_high_source_volume=" + config.propellerFarCompensateHighSourceVolume.get());
        lines.add("propeller_far_source_volume_compensation_strength=" + config.propellerFarSourceVolumeCompensationStrength.get());
        lines.add("propeller_far_field_skip_reverb_after_distance=" + config.propellerFarFieldSkipReverbAfterDistance.get());
        lines.add("distant_horizons_far_propeller_occlusion_enabled=" + config.distantHorizonsFarPropellerOcclusionEnabled.get());
        lines.add("distant_horizons_far_propeller_min_distance=" + config.distantHorizonsFarPropellerMinDistance.get());
        lines.add("distant_horizons_far_propeller_probe_interval_ticks=" + config.distantHorizonsFarPropellerProbeIntervalTicks.get());
        lines.add("distant_horizons_far_propeller_max_strength=" + config.distantHorizonsFarPropellerMaxStrength.get());
        lines.add("distant_horizons_far_propeller_gain_at_full_occlusion=" + config.distantHorizonsFarPropellerGainAtFullOcclusion.get());
        lines.add("distant_horizons_far_propeller_cutoff_at_full_occlusion=" + config.distantHorizonsFarPropellerCutoffAtFullOcclusion.get());
        lines.add("distant_horizons_far_propeller_max_ray_length=" + config.distantHorizonsFarPropellerMaxRayLength.get());
        lines.add("distant_horizons_far_propeller_debug_logging=" + config.distantHorizonsFarPropellerDebugLogging.get());
        lines.add("sound_physics_max_sound_starts_per_tick=" + config.soundPhysicsMaxSoundStartsPerTick.get());
        lines.add("sound_physics_max_debug_rays_per_tick=" + config.soundPhysicsMaxDebugRaysPerTick.get());
        lines.add("sound_physics_impact_burst_dedupe_enabled=" + config.soundPhysicsImpactBurstDedupeEnabled.get());
        lines.add("sound_physics_impact_burst_dedupe_apply_to_tickable_sounds=" + config.soundPhysicsImpactBurstDedupeApplyToTickableSounds.get());
        lines.add("sound_physics_impact_burst_dedupe_radius=" + config.soundPhysicsImpactBurstDedupeRadius.get());
        lines.add("sound_physics_impact_burst_dedupe_ticks=" + config.soundPhysicsImpactBurstDedupeTicks.get());
        return lines;
    }

    public static String criticalValuesSummary() {
        SoundPhysicsConfig config = SoundPhysicsMod.CONFIG;
        if (config == null) {
            return "SPRA_PATCH_ID=" + SoundPhysicsMod.SPRA_PATCH_ID + ", mode=" + DiagnosticRuntimeOverrides.mode().commandName() + ", config=not_initialized";
        }

        return "SPRA_PATCH_ID=" + SoundPhysicsMod.SPRA_PATCH_ID
                + ", mode=" + DiagnosticRuntimeOverrides.mode().commandName()
                + ", enabled=" + DiagnosticRuntimeOverrides.soundPhysicsEnabled(config)
                + ", render_occlusion=" + DiagnosticRuntimeOverrides.renderOcclusion(config)
                + ", render_sound_bounces=" + DiagnosticRuntimeOverrides.renderSoundBounces(config)
                + ", runtime_logging=(" + RuntimeLoggingController.statusText(config) + ")"
                + ", sound_physics_trace_logging=" + DiagnosticRuntimeOverrides.traceLoggingEnabled(config)
                + ", openal_error_checks=" + DiagnosticRuntimeOverrides.openAlErrorChecksEnabled(config)
                + ", adaptive_reflection_budget_enabled=" + config.adaptiveReflectionBudgetEnabled.get()
                + ", sable_acoustics_enabled=" + DiagnosticRuntimeOverrides.sableAcousticsEnabled(config)
                + ", force_root_acoustic_provider=" + DiagnosticRuntimeOverrides.forceRootAcousticProvider(config)
                + ", doppler_enabled=" + DiagnosticRuntimeOverrides.dopplerEnabled(config)
                + ", sound_physics_apply_to_records=" + config.soundPhysicsApplyToRecords.get()
                + ", record_acoustic_update_interval_ticks=" + config.recordAcousticUpdateIntervalTicks.get()
                + ", sound_physics_apply_to_positional_ambient_machinery=" + config.soundPhysicsApplyToPositionalAmbientMachinery.get()
                + ", doppler_apply_to_positional_ambient_machinery=" + config.dopplerApplyToPositionalAmbientMachinery.get()
                + ", propeller_long_range_enabled=" + config.propellerLongRangeEnabled.get()
                + ", propeller_long_range_profile=" + config.propellerLongRangeProfile.get()
                + ", propeller_long_range_max_distance=" + config.propellerLongRangeMaxDistance.get()
                + ", propeller_far_field_enabled=" + config.propellerFarFieldEnabled.get()
                + ", distant_horizons_far_propeller_occlusion_enabled=" + config.distantHorizonsFarPropellerOcclusionEnabled.get()
                + ", raw(enabled=" + config.enabled.get()
                + ", render_occlusion=" + config.renderOcclusion.get()
                + ", render_sound_bounces=" + config.renderSoundBounces.get()
                + ", sound_physics_trace_logging=" + config.soundPhysicsTraceLogging.get()
                + ", openal_error_checks=" + config.openAlErrorChecks.get()
                + ", adaptive_reflection_budget_enabled=" + config.adaptiveReflectionBudgetEnabled.get()
                + ", sable_acoustics_enabled=" + config.sableAcousticsEnabled.get()
                + ", force_root_acoustic_provider=" + config.forceRootAcousticProvider.get()
                + ", doppler_enabled=" + config.dopplerEnabled.get() + ")";
    }

    private static String lastModifiedText(Path path) {
        try {
            if (!Files.isRegularFile(path)) {
                return "missing";
            }
            return Files.getLastModifiedTime(path).toInstant().toString();
        } catch (IOException exception) {
            return "unavailable: " + exception.getMessage();
        }
    }

}
